### ISSUE TITLE
Error when create Issue with group_watcher

### ISSUE THREAD

**Issue by DanilaFH** [piccio/redmine_watchers_groups#6]
When i try to create new Issue with group_watchers, i get an error:

```
ActiveRecord::RecordNotFound (Couldn't find User with 'id'=[6260] [WHERE "users"."type" IN ('User', 'AnonymousUser')]):

lib/plugins/acts_as_watchable/lib/acts_as_watchable.rb:66:in `watcher_user_ids='
app/models/issue.rb:446:in `assign_attributes'
app/models/issue.rb:602:in `safe_attributes='
plugins/redmine_watchers_groups/lib/redmine_watchers_groups/issue_patch.rb:30:in `safe_attributes='
app/controllers/issues_controller.rb:546:in `build_new_issue_from_params'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

(where 6260 is a group_id)

Redmine version 4.1.1.stable
Plugin version 2.0.0

**Comment by DanilaFH** [comment]
Looks like work fine on version 4.2.2
